name: sunny_graphql
version: 1.14.0
homepage: https://github.com/ericmartineau/sunny_graphql
description: GraphQL generation and query base library for sunny
environment: 
  sdk: '>=2.17.0 <3.0.0'
dependencies: 
  logging: 1.2.0
  equatable: ^2.0.5
  pedantic: ^1.11.1
  inflection3: ^0.5.3+2
  graphql_flutter: ^5.2.0-beta.3
  gql: ^1.0.0
  uri: ^1.0.0
  sunny_sdk_core: 
    path: /Users/ericm/aesthetika/checkout/SunnyApp/sunny_sdk_core
  collection_diff: 
    path: /Users/ericm/aesthetika/checkout/SunnyApp/collection_diff
  dartxx: 
    path: /Users/ericm/aesthetika/checkout/ericmartineau/dartxx
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: null
