name: sunny_graphql
version: 1.14.0
homepage: https://github.com/ericmartineau/sunny_graphql
description: GraphQL generation and query base library for sunny
environment: 
  sdk: '>=2.17.0 <3.0.0'
dependencies: 
  logging: ^1.0.2
  equatable: ^2.0.5
  pedantic: ^1.11.1
  graphql_flutter: ^5.1.1-beta.4
  gql: ^0.14.0
  inflection3: ^0.5.3+2
  uri: ^1.0.0
  collection_diff: 
    git: 
      url: git@github.com:SunnyApp/collection_diff
      ref: trippi_app
  sunny_sdk_core: 
    git: 
      url: git@github.com:SunnyApp/sunny_sdk_core.git
      ref: trippi_app
  dartxx: 
    git: 
      url: git@github.com:ericmartineau/dartxx.git
      ref: trippi_app
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: null
