name: sunny_graphql
version: 1.14.0
homepage: https://github.com/ericmartineau/sunny_graphql
description: GraphQL generation and query base library for sunny
environment: 
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=1.17.0'
dependencies: 
  logging: ^1.0.2
  equatable: ^2.0.3
  pedantic: ^1.11.1
  uri: ^1.0.0
  sunny_sdk_core: ^2.5.0
  collection_diff: ^2.0.3+6
  inflection3: ^0.5.3+2
  graphql_flutter: ^5.0.0
  gql: ^0.13.0
  dartxx: ^0.5.5
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: null
