name: sunny_graphql
version: 1.14.0
homepage: https://github.com/ericmartineau/sunny_graphql
description: GraphQL generation and query base library for sunny
environment: 
  sdk: '>=2.17.0 <3.0.0'
dependencies: 
  logging: ^1.0.2
  equatable: ^2.0.5
  pedantic: ^1.11.1
  graphql_flutter: ^5.1.1-beta.4
  gql: ^0.13.0
  inflection3: ^0.5.3+2
  uri: 
    path: /Users/ericm/sunny/local_plugins/uri.dart
  collection_diff: 
    path: /Users/ericm/sunny/local_plugins/collection_diff
  sunny_sdk_core: 
    path: /Users/ericm/sunny/local_plugins/sunny_sdk_core
  dartxx: 
    path: /Users/ericm/sunny/local_plugins/dartxx
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: null
