name: example
description: A sample project using graphql generator.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.13.0 <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  graphql: ^5.0.0
  provider: ^6.0.1
#  ferry: ^0.10.5-dev.0
  logging_config: ^0.6.7+7
  logging: ^1.0.2
  sunny_graphql:
    path: ../../
  flutter:
    sdk: flutter
  sunny_sdk_core: ^2.0.0+10
  pfile: ^2.1.0+4
  cupertino_icons: ^1.0.3
  material_design_icons_flutter: ^4.0.5955

dependency_overrides:
  meta: ^1.7.0
  analyzer: ^2.1.0
#  ferry_cache: ^0.5.5
#  rxdart: ^0.27.1

dev_dependencies:
  build_runner: any
  flutter_test:
    sdk: flutter
#  gql_build: ^0.3.0-alpha.0
#  ferry_generator: ^0.5.0-dev.1
  sunny_graphql_generator:
    path: ../



