targets:
  $default:
    builders:
      sunny_graphql_generator:
        enabled: true
      sunny_graphql_generator|sunny_graphql_api_generator:
        enabled: true
      sunny_graphql_generator|sunny_graphql_meta_generator:
        enabled: true


builders:
  sunny_graphql_meta_generator:
    import: "package:sunny_graphql_generator/build.dart"
    builder_factories:
      - "sunnyGraphQLMeta"
    auto_apply: dependents
    build_extensions: { ".dart": [ ".meta.g.part" ] }
    build_to: source
    applies_builders:
      - "source_gen"


  sunny_graphql_api_generator:
    import: "package:sunny_graphql_generator/build.dart"
    builder_factories:
      - "sunnyGraphQLAPI"
    build_extensions: { ".dart": [ ".api.g.part" ] }
    auto_apply: dependents
    build_to: source
    applies_builders:
      - "source_gen"

  sunny_graphql_generator:
    import: "package:sunny_graphql_generator/build.dart"
    builder_factories:
      - "sunnyGraphQLImplementation"
    build_extensions: { ".dart": [ ".impl.g.part" ] }
    auto_apply: dependents
    build_to: source
    applies_builders:
      - "source_gen"










