name: sunny_graphql_generator
description: >
  A generator for creating models and services to hit graphql endpoints
version: 1.11.0

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  logging: ^1.0.1
  gql: ^0.13.0
  flutter_degen: ^0.8.0+2
  build_runner: ^2.1.2
  source_gen: ^1.1.0
  build: ^2.1.0
  code_builder: ^4.1.0
  dart_style: ^2.0.3
  analyzer: ^2.2.0
  dartxx: ^0.5.0+2
  flexidate: ^0.6.0+2
  meta: ^1.7.0
  pedantic: ^1.11.1
  sunny_graphql:
    path: ../
  uri: ^1.0.0

dev_dependencies:
  build_config: ^1.0.0

dependency_overrides:
  meta: ^1.7.0
  sunny_graphql:
    path: ../
flutter:
  uses-material-design: false
